---
graphics: yes
name: "Jordan Mark"
surname: "Barbone, M.A."
# Default head color won't show
headcolor: 414141
position: "Data Scientist, R Developer"
address: "West Chester, PA"
phone: "+1 (610) 675-8922"
www: jmbarbone.github.io
email: "jmbarbone@gmail.com"
# twitter: jmbarbone
github: jmbarbone
linkedin: jmbarbone
aboutme: "R programmer with experience in statistical programming, monitoring, and report automation in cognitive and CNS clinical trials"
date: 'Last updated `r format(Sys.Date(), "%B %Y")`'
csl: "csl/apa6-cv.csl"
nocite: "@*"
knit: bookdown::render_book
bibliography_publications: "bib/publications.bib"
bibliography_thesis: "bib/thesis.bib"
bibliography_posters_signant: "bib/posters_signant.bib" 
bibliography_posters_wcupa: "bib/posters_wcupa.bib"
bibliography_posters_madrigal: "bib/posters_madrigal.bib"
---

```{r setup, include=FALSE, cache = FALSE}
options(
  tinytex.verbose = TRUE,
  tidyverse.quiet = TRUE
)
library(knitr)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(bookdown)
```

```{r FUNS}
col_to_rowname <- function(x, col = 1L) {
  if (is.character(col)) {
    col <- which(colnames(x) == col)
  }
  
  if (inherits(x, "tbl_df")) {
    x <- as.data.frame(x)
  }
  
  y <- x[[1]]
  lens <- tapply(y, y, length)
  bad <- lens > 1L
  
  if (any(bad)) {
    stop("Multiple entriess found for column, cannot convert to rownames: ",
         paste(names(lens)[bad], collapse = "\n"),
         call. = FALSE
    )
  }
  
  rownames(x) <- y
  x <- x[-col]
  x
}

# RefManageR::as.BibEntry() assumes a different style
adjust_author_name <- function(a) {
  splits <- strsplit(a, " and ")[[1]]
  switches <- sapply(
    splits,
    function(x) {
      x <- gsub("(^.*)[,\\s](.*$)", "\\2 \\1", x)
      x <- gsub("\\s+", " ", x)
      trimws(x)
    })
  paste(switches, collapse = " and ")
}

adjust_author_names <- function(names) {
  sapply(names, adjust_author_name)
}
```


```{r get and write bibs}
# All references saved
bib_file <- mark::file_path(
  Sys.getenv("R_USER"),
  "GitHub",
  "bib-references",
  "references.bib",
  check = TRUE
)

bib <- mark::read_bib(bib_file, skip = 3L)

bib_df <- bib %>%
  as_tibble() %>%
  filter(
    str_detect(author, "Barbone"),
    str_detect(keywords, "_DRAFT_", negate = TRUE)
  ) %>%
  rename(bibtype = field) %>%
  mutate(author = adjust_author_names(author),
         booktitle = if_else(bibtype == "inproceedings",
                             note,
                             booktitle),
         month = match(month, month.abb)) %>%
  col_to_rowname()

# Remove columns so month will show and be ordered correctly?
cols <- c("pages", "journal", "publisher", "number", "volume")
inp <- bib_df$bibtype == "inproceedings"
for (i in cols) {
  bib_df[[i]][inp] <- NA_character_
}

nas <- is.na(bib_df$keywords)
keywords <- strsplit(bib_df$keywords, ", ")
outs <- sapply(keywords, function(x) {
  !any(x %in% c("Signant Health", "Madrigal", "wcupa"))
})
bad <- nas | outs
if (any(bad)) {
  stop("These references are missing keywords: ",
       paste(rownames(bib_df)[bad], collapse = " & "),
       call. = FALSE)
}

bib_df %>%
  filter(bibtype == "article") %>%
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib(file = "bib/publications.bib")

bib_df %>%
  filter(bibtype == "mastersthesis") %>%
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib(file = "bib/thesis.bib")

posters <- bib_df %>%
  filter(bibtype == "inproceedings")

posters %>%
  filter(str_detect(keywords, "Signant Health")) %>%
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib(file = "bib/posters_signant.bib")

posters %>%
  filter(str_detect(keywords, "Madrigal")) %>%
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib(file = "bib/posters_madrigal.bib")

posters %>%
  filter(str_detect(keywords, "wcupa")) %>%
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib(file = "bib/posters_wcupa.bib")
```
