#!/usr/bin/env -S Rscript

library(scribe, lib = Sys.getenv("R_LIBS_SCRIBE"))
devtools::load_all()

pandoc::pandoc_activate("3.4")

ca <- command_args()
ca$add_argument(
  "outputs",
  default = c("resume", "cv"),
  info = "Outputs to render"
)

args <- ca$parse()

for (output in args$outputs) {
  switch(
    output,
    resume = quarto::quarto_render(
      "resume/resume.qmd",
      output_file = "Barbone-Resume.pdf",
      execute_dir = "resume"
    ),
    cv = quarto::quarto_render(
      "cv/compact-cv.qmd",
      output_file = "Barbone-CV.pdf",
      execute_dir = "cv"
    ),
    stop("Unknown output: ", output)
  )
}

withr::with_options(
  list(cli.width = 80),
  sessioninfo::session_info(to_file = TRUE)
)
