#!/usr/bin/env -S Rscript

library(scribe, lib = Sys.getenv("R_LIBS_SCRIBE"))
devtools::load_all()

ca <- command_args()
ca$add_argument(
  "outputs",
  default = c("resume", "cv"),
  info = "Outputs to render"
)
ca$add_argument(
  "-u", "--update",
  action = "flag",
  info = "Update cls"
)

args <- ca$parse()

for (output in args$outputs) {
  switch(
    output,
    resume = {
      if (args$update) {
        cat("Updating moderncv.cls\n")
        "https://raw.githubusercontent.com/moderncv/moderncv/master/moderncv.cls" |>
          readLines() |>
          writeLines("resume/moderncv.cls")
      }

      with_cleanup("resume", {
        bookdown::render_book(
          input = "resume/index.Rmd",
          output_format = "vitae::moderncv",
          config_file = "resume/_bookdown.yaml"
        )
      })

      fs::file_move("resume/Barbone-Resume.pdf", "Barbone-Resume.pdf")

    },
    cv = {
      if (args$update) {
        cat("Updating awecomecv.cls\n")
        "https://raw.githubusercontent.com/posquit0/Awesome-CV/master/awesome-cv.cls" |>
          readLines() |>
          writeLines("cv/awesomecv.cls")
      }

      with_cleanup("cv", {
        bookdown::render_book(
          input = "cv/index.Rmd",
          output_format = "vitae::awesomecv",
          config_file = "cv/_bookdown.yaml"
        )
      })

      fs::file_move("cv/Barbone-CV.pdf", "Barbone-CV.pdf")
    }
  )
}
