#!/usr/bin/env bash

sudo apt update && sudo apt update -y
sudo apt install texlive-full -y

mkdir -p ~/R/cv-library

R --no-save <<EOF
devtools::load_all()
update_cv_library()

pak::pak("pandoc")
pandoc::pandoc_install("3.1.3", force = TRUE)
# pandoc::pandoc_install(force = TRUE)

pak::pak("github::mitchelloharawild/vitae@v0.5.3)
pak::pak()
EOF

curl -Z \
  https://raw.githubusercontent.com/pandoc/lua-filters/master/multiple-bibliographies/multiple-bibliographies.lua \
  -o lua/multiple-bibliographies.lua \
  "https://raw.githubusercontent.com/moderncv/moderncv/master/moderncv.cls" \
  -o resume/moderncv.cls \
  https://raw.githubusercontent.com/posquit0/Awesome-CV/master/awesome-cv.cls \
  -o cv/awesomecv.cls