#!/usr/bin/env bash

sudo apt update && sudo apt update -y
sudo apt install texlive-full -y

rm -fr ~/R/cv-library
mkdir -p ~/R/cv-library

R --no-save <<EOF
pak::pak(c("pandoc", "tinytex"))
pandoc::pandoc_install("3.4", force = TRUE)
if (tinytex::is_tinytex()) {
  tinytex::reinstall_tinytex(version = "latest", force = TRUE)
} else { 
  tinytex::install_tinytex(version = "latest", force = TRUE)
}


pak::pak()

devtools::load_all()
update_cv_library()


EOF

curl -Z \
  https://raw.githubusercontent.com/pandoc/lua-filters/master/multiple-bibliographies/multiple-bibliographies.lua \
  -o lua/multiple-bibliographies.lua \
  "https://raw.githubusercontent.com/moderncv/moderncv/master/moderncv.cls" \
  -o resume/moderncv.cls \
  https://raw.githubusercontent.com/mitchelloharawild/vitae/refs/heads/master/inst/rmarkdown/templates/awesomecv/skeleton/awesome-cv.tex \
  -o cv/awesome-cv.tex \
  https://raw.githubusercontent.com/citation-style-language/styles/master/apa-cv.csl \
  -o csl/apa-cv.csl
