---
graphics: yes
name: "Jordan Mark"
surname: "Barbone, M.A."
headcolor: 414141
position: "Data Scientist, R Developer"
address: "West Chester, PA"
phone: "+1 610 675 8922"
www: jmbarbone.github.io
email: "jmbarbone@gmail.com; jbarbone@cogstate.com"
github: jmbarbone
linkedin: jmbarbone
aboutme: |
  R programmer with experience in statistical programming, monitoring, and report automation in cognitive and CNS clinical trials
  \newline
  \newline
  For an updated version see \href{https://github.com/jmbarbone/barbone-cv}{\texttt{jmbarbone/barbone-cv}}
date: |
  Last updated `r format(Sys.Date(), "%B %Y")`
csl: "../csl/apa-cv.csl"
nocite: "@*"
bibliography_publications: "../bib/publications.bib"
bibliography_thesis: "../bib/thesis.bib"
bibliography_posters_signant: "../bib/posters_signant.bib"
bibliography_posters_wcupa: "../bib/posters_wcupa.bib"
bibliography_posters_madrigal: "../bib/posters_madrigal.bib"
bibliography_posters_cogstate: "../bib/posters_cogstate.bib"
bibliography_packages: "../bib/packages.bib"
editor_options:
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false
#| cache: false
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

# devtools::load_all()
BUILD <- "cv"
```

```{r}
#| label: bibs get
bibs <- mark::read_bib("https://raw.githubusercontent.com/jmbarbone/bib-references/master/references.bib", skip = 3L)
```

```{r}
#| label: bibs formatting
bib_df <-
  bibs |>
  as_tibble() |>
  filter(
    str_detect(author, "Barbone"),
    str_detect(keywords, "_DRAFT_", negate = TRUE)
  ) |>
  rename(bibtype = field) |>
  mutate(
    author = adjust_author_names(author),
    booktitle = if_else(
      bibtype == "inproceedings",
      note,
      booktitle
    ),
    month = match(month, month.abb),
    keywords = tolower(keywords),
  ) |>
  arrange(desc(year), desc(month)) |>
  as.data.frame() |>
  mark::to_row_names()

# Remove columns so month will show and be ordered correctly?
cols <- c("pages", "journal", "publisher", "number", "volume")
inp <- bib_df$bibtype == "inproceedings"

for (i in cols) {
  bib_df[[i]][inp] <- NA_character_
}

keywords <- strsplit(bib_df$keywords, ", ")
outs <- sapply(keywords, function(i) {
  all(i %out% c("signant health", "madrigal", "wcupa", "cogstate"))
})
bad <- is.na(bib_df$keywords) | outs

if (any(bad)) {
  stop(
    "These references are missing keywords: ",
    paste(rownames(bib_df)[bad], collapse = " & ")
  )
}


bib_df |>
  filter(bibtype == "article") |>
  RefManageR::as.BibEntry() |>
  RefManageR::WriteBib(file = bib("publications"))

bib_df |>
  filter(bibtype == "mastersthesis") |>
  RefManageR::as.BibEntry() |>
  RefManageR::WriteBib(file = bib("thesis"))

posters <-
  bib_df |>
  filter(bibtype == "inproceedings")

posters |>
  filter(str_detect(keywords, "cogstate")) |>
  RefManageR::as.BibEntry() |>
  RefManageR::WriteBib(file = bib("posters_cogstate"))

posters |>
  filter(str_detect(keywords, "signant health")) |>
  RefManageR::as.BibEntry() |>
  RefManageR::WriteBib(file = bib("posters_signant"))

posters |>
  filter(str_detect(keywords, "madrigal")) |>
  RefManageR::as.BibEntry() |>
  RefManageR::WriteBib(file = bib("posters_madrigal"))

posters |>
  filter(str_detect(keywords, "wcupa")) |>
  RefManageR::as.BibEntry() |>
  RefManageR::WriteBib(file = bib("posters_wcupa"))
```
