---
graphics: yes
name: "Jordan Mark"
surname: "Barbone, M.A."
headcolor: 414141
position: "Data Scientist, R Developer"
address: "West Chester, PA"
phone: "+1 610 675 8922"
www: jmbarbone.github.io
email: "jmbarbone@gmail.com; jbarbone@cogstate.com"
github: jmbarbone
linkedin: jmbarbone
aboutme: "R programmer with experience in statistical programming, monitoring, and report automation in cognitive and CNS clinical trials"
date: 'Last updated `r format(Sys.Date(), "%B %Y")`'
editor_options:
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false
#| cache: false
knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE
)

options(
  tinytex.verbose = TRUE,
  tidyverse.quiet = TRUE
)

library(knitr)
library(tidyverse)
library(vitae)
library(bookdown)
library(mark)

BUILD <- "resume"
```

```{r}
#| label: funs
read_yaml <- function(x) {
    x |>
    yaml::read_yaml() |>
    purrr::pluck(1) |>
    purrr::map(tibble::as_tibble) |>
    purrr::list_rbind()
}
```